Controllers/ProductsCommentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CuaHangDoAn.Data;
using CuaHangDoAn.Models;

namespace CuaHangDoAn.Controllers
{
    //[Comment Feature]
    public class ProductsCommentsController : Controller
    {
        private readonly CuaHangDoAnContext _context;

        public ProductsCommentsController(CuaHangDoAnContext context)
        {
            _context = context;
        }

        // GET: ProductsComments
        public async Task<IActionResult> Index()
        {
            var cuaHangDoAnContext = _context.ProductsComments.Include(p => p.Product);
            return View(await cuaHangDoAnContext.ToListAsync());
        }

        // GET: ProductsComments/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.ProductsComments == null)
            {
                return NotFound();
            }

            var productsComments = await _context.ProductsComments
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productsComments == null)
            {
                return NotFound();
            }

            return View(productsComments);
        }

        // GET: ProductsComments/Create
        public IActionResult Create()
        {
            ViewData["ProductID"] = new SelectList(_context.Products, "Id", "Name");
            return RedirectToAction("Index","Home");
        }

        // POST: ProductsComments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Comment,CreatedDate,Rating,ProductID")] ProductsComments productsComments, string returnUrl = null)
        {
            if (ModelState.IsValid)
            {
                _context.Add(productsComments);
                DateTime today = DateTime.Now;
                productsComments.CreatedDate = today;
                await _context.SaveChangesAsync();
                return LocalRedirect(returnUrl);
            }
            return LocalRedirect(returnUrl);
        }

        // GET: ProductsComments/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.ProductsComments == null)
            {
                return NotFound();
            }

            var productsComments = await _context.ProductsComments.FindAsync(id);
            if (productsComments == null)
            {
                return NotFound();
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "Id", "Name", productsComments.ProductID);
            return View(productsComments);
        }

        // POST: ProductsComments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Comment,CreatedDate,Rating,ProductID")] ProductsComments productsComments)
        {
            if (id != productsComments.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(productsComments);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsCommentsExists(productsComments.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProductID"] = new SelectList(_context.Products, "Id", "Name", productsComments.ProductID);
            return View(productsComments);
        }

        // GET: ProductsComments/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.ProductsComments == null)
            {
                return NotFound();
            }

            var productsComments = await _context.ProductsComments
                .Include(p => p.Product)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productsComments == null)
            {
                return NotFound();
            }

            return View(productsComments);
        }

        // POST: ProductsComments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.ProductsComments == null)
            {
                return Problem("Entity set 'CuaHangDoAnContext.ProductsComments'  is null.");
            }
            var productsComments = await _context.ProductsComments.FindAsync(id);
            if (productsComments != null)
            {
                _context.ProductsComments.Remove(productsComments);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductsCommentsExists(int id)
        {
          return (_context.ProductsComments?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_CommentBox.cshtml
<dl class="dl-horizontal col-8">
    <dt>
        Comment
    </dt>
    @*[Comment Feature]*@
    <dd>
        <div class="commentBox">
            @*@using (Html.BeginForm("Create", "ProductsComments", FormMethod.Post, new { onsubmit = "return SubmitComment()", @asp-route-returnUrl }))*@
            <form asp-action="Create" asp-controller="ProductsComments" method="post" asp-route-returnUrl="@ViewBag.returnUrl">
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    <div class="form-group">
                        <label class="col-md-12 control-label">
                            Your rating <span style="font-weight:normal;">(1 start is bad, 5 star is good)</span>
                        </label>
                        <div class="col-md-12">
                            <div onmouseout="CRateSelected()">
                                <span class="starFade" id="Rate1" onclick="CRate(1)" onmouseover="CRateOver(1)" onmouseout="CRateOut(1)"></span><span class="starFade" id="Rate2" onclick="CRate(2)" onmouseover="CRateOver(2)" onmouseout="CRateOut(2)"></span><span class="starFade" id="Rate3" onclick="CRate(3)" onmouseover="CRateOver(3)" onmouseout="CRateOut(3)"></span><span class="starFade" id="Rate4" onclick="CRate(4)" onmouseover="CRateOver(4)" onmouseout="CRateOut(4)"></span><span class="starFade" id="Rate5" onclick="CRate(5)" onmouseover="CRateOver(5)" onmouseout="CRateOut(5)"></span>
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <textarea name="Comment" id="Comment" required rows="5" style="width:100%;" class="form-control"></textarea>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="hidden" name="ProductID" value="@ViewBag.ProductID" />
                            <input type="hidden" name="Rating" id="Rating" value="0" />
                            <input type="submit" id="btnRegister" name="btnRegister" value="Submit Comment" class="btn btn-warning" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </dd>

</dl>
<script>
    function SubmitComment() {
        if ($("#Rating").val() == "0") {
            alert("Please rate this service provider.");
            return false;
        }
        else {
            return true;
        }
    }

    function CRate(r) {
        $("#Rating").val(r);
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
        // unselect remaining
        for (var i = r + 1; i <= 5; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateOver(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }

    function CRateOut(r) {
        for (var i = 1; i <= r; i++) {
            $("#Rate" + i).attr('class', 'starFade');
        }
    }

    function CRateSelected() {
        var setRating = $("#Rating").val();
        for (var i = 1; i <= setRating; i++) {
            $("#Rate" + i).attr('class', 'starGlow');
        }
    }
</script>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ogani | Template</title>

    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">

    <!-- Css Styles -->
    <link rel="stylesheet" href="~/UserAsset/css/bootstrap.min.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/font-awesome.min.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/elegant-icons.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/nice-select.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/jquery-ui.min.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/owl.carousel.min.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/slicknav.min.css" type="text/css">
    <link rel="stylesheet" href="~/UserAsset/css/style.css" type="text/css">
</head>

<body>
    <!-- Page Preloder -->
    <div id="preloder">
        <div class="loader"></div>
    </div>

    <!-- Humberger Begin -->
    <div class="humberger__menu__overlay"></div>
    <div class="humberger__menu__wrapper">
        <div class="humberger__menu__logo">
            <a href="~/"><img src="~/UserAsset/img/logo.png" alt=""></a>
        </div>
        <div class="humberger__menu__cart">
            <ul>
                <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                <li><a href="#"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
            </ul>
            <div class="header__cart__price">item: <span>$150.00</span></div>
        </div>
        <div class="humberger__menu__widget">
            <div class="header__top__right__language">
                <img src="~/UserAsset/img/language.png" alt="">
                <div>English1</div>
                <span class="arrow_carrot-down"></span>
                @*<ul>
                <li><a asp-action="MyProfile">Profile</a></li>
                <li><a href="#">English</a></li>
                </ul>*@
            </div>
            <div class="header__top__right__auth">
                <a href="#"><i class="fa fa-user"></i> Login</a>
            </div>
        </div>
        <nav class="humberger__menu__nav mobile-menu">
            <ul>
                <li class="active"><a href="./">Home</a></li>
                <li><a href="./shop-grid.html">Shop</a></li>
                <li>
                    <a href="#">Pages</a>
                    <ul class="header__menu__dropdown">
                        <li><a href="./shop-details.html">Shop Details</a></li>
                        <li><a href="~/Home/shoping_cart">Shoping Cart</a></li>
                        <li><a href="./checkout.html">Check Out</a></li>
                        <li><a href="./blog-details.html">Blog Details</a></li>
                    </ul>
                </li>
                <li><a href="./blog.html">Blog</a></li>
                <li><a href="./contact.html">Contact</a></li>
            </ul>
        </nav>
        <div id="mobile-menu-wrap"></div>
        <div class="header__top__right__social">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-pinterest-p"></i></a>
        </div>
        <div class="humberger__menu__contact">
            <ul>
                <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                <li>Free Shipping for all Order of $99</li>
            </ul>
        </div>
    </div>
    <!-- Humberger End -->
    <!-- Header Section Begin -->
    <header class="header">
        <div class="header__top">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__left">
                            <ul>
                                <li><i class="fa fa-envelope"></i> hello@colorlib.com</li>
                                <li>Free Shipping for all Order of $99</li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="header__top__right">
                            <div class="header__top__right__social">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-pinterest-p"></i></a>
                            </div>

                            <div class="header__top__right__auth">

                                @if (User.Identity.IsAuthenticated)
                                {
                                    <div class="header__top__right__language">
                                        <img src="~/UserAsset/img/language.png" alt="">
                                        <div>@User.Identity.Name</div>
                                        <span class="arrow_carrot-down"></span>
                                        <ul>
                                            <li><a asp-action="MyProfile"> MyProfile</a></li>
                                            <li><a asp-area="Identity" asp-controller="account" asp-action="Manage">
                                                    Profile</a></li>
                                            <li><a asp-action="ListOrder"> My Order</a></li>
                                            <li>
                                                <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout"
                                                    asp-route-returnUrl="@Url.Page("/", new { area = "" })" method="post">
                                                    <button type="submit"
                                                        class="nav-link btn btn-link text-light">Logout</button>
                                                </form>
                                            </li>
                                        </ul>
                                    </div>

                                }
                                else
                                {
                                    <partial name="_LoginPartial.cshtml" />
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="header__logo">
                        <a href="./"><img src="~/UserAsset/img/logo.png" alt=""></a>
                    </div>
                </div>
                <div class="col-lg-6">
                    <nav class="header__menu">
                        <ul>
                            <li class="active"><a href="./">Home</a></li>
                            <li><a href="./shop-grid.html">Shop</a></li>
                            <li>
                                <a href="#">Pages</a>
                                <ul class="header__menu__dropdown">
                                    <li><a href="./shop-details.html">Shop Details</a></li>
                                    <li><a href="~/Home/shoping_cart">Shoping Cart</a></li>
                                    <li><a href="./checkout.html">Check Out</a></li>
                                    <li><a href="./blog-details.html">Blog Details</a></li>
                                </ul>
                            </li>
                            <li><a href="./blog.html">Blog</a></li>
                            <li><a href="./contact.html">Contact</a></li>
                        </ul>
                    </nav>
                </div>
                <div class="col-lg-3">
                    <div class="header__cart">
                        <ul>
                            <li><a href="#"><i class="fa fa-heart"></i> <span>1</span></a></li>
                            <li><a href="~/Home/shoping_cart"><i class="fa fa-shopping-bag"></i> <span>3</span></a></li>
                        </ul>
                        <div class="header__cart__price">item: <span>$150.00</span></div>
                    </div>
                </div>
            </div>
            <div class="humberger__open">
                <i class="fa fa-bars"></i>
            </div>
        </div>
    </header>
    <!-- Header Section End -->
    <!-- Hero Section Begin -->
    @RenderBody()
    <!-- Blog Section End -->
    <!-- Footer Section Begin -->
    <footer class="footer spad">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6">
                    <div class="footer__about">
                        <div class="footer__about__logo">
                            <a href="./index.html"><img src="~/UserAsset/img/logo.png" alt=""></a>
                        </div>
                        <ul>
                            <li>Address: 60-49 Road 11378 New York</li>
                            <li>Phone: +65 11.188.888</li>
                            <li>Email: hello@colorlib.com</li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                    <div class="footer__widget">
                        <h6>Useful Links</h6>
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">About Our Shop</a></li>
                            <li><a href="#">Secure Shopping</a></li>
                            <li><a href="#">Delivery infomation</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Our Sitemap</a></li>
                        </ul>
                        <ul>
                            <li><a href="#">Who We Are</a></li>
                            <li><a href="#">Our Services</a></li>
                            <li><a href="#">Projects</a></li>
                            <li><a href="#">Contact</a></li>
                            <li><a href="#">Innovation</a></li>
                            <li><a href="#">Testimonials</a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12">
                    <div class="footer__widget">
                        <h6>Join Our Newsletter Now</h6>
                        <p>Get E-mail updates about our latest shop and special offers.</p>
                        <form action="#">
                            <input type="text" placeholder="Enter your mail">
                            <button type="submit" class="site-btn">Subscribe</button>
                        </form>
                        <div class="footer__widget__social">
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="footer__copyright">
                        <div class="footer__copyright__text">
                            <p>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                                Copyright &copy;
                                <script>document.write(new Date().getFullYear());</script> All rights reserved | This
                                template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a
                                    href="https://colorlib.com" target="_blank">Colorlib</a>
                                <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            </p>
                        </div>
                        <div class="footer__copyright__payment"><img src="~/UserAsset/img/payment-item.png" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer Section End -->
    <!-- Js Plugins -->
    <script src="~/UserAsset/js/jquery-3.3.1.min.js"></script>
    <script src="~/UserAsset/js/bootstrap.min.js"></script>
    <script src="~/UserAsset/js/jquery.nice-select.min.js"></script>
    <script src="~/UserAsset/js/jquery-ui.min.js"></script>
    <script src="~/UserAsset/js/jquery.slicknav.js"></script>
    <script src="~/UserAsset/js/mixitup.min.js"></script>
    <script src="~/UserAsset/js/owl.carousel.min.js"></script>
    <script src="~/UserAsset/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>

</html>

Views/Shared/_SidenarPartialView.cshtml
@*<div class="col-lg-3">
    <div class="hero__categories">
        <div class="hero__categories__all">
            <i class="fa fa-bars"></i>
            <span>All departments</span>
        </div>
        <ul>
            <li><a href="#">Fresh Meat</a></li>
            <li><a href="#">Vegetables</a></li>
            <li><a href="#">Fruit & Nut Gifts</a></li>
            <li><a href="#">Fresh Berries</a></li>
            <li><a href="#">Ocean Foods</a></li>
            <li><a href="#">Butter & Eggs</a></li>
            <li><a href="#">Fastfood</a></li>
            <li><a href="#">Fresh Onion</a></li>
            <li><a href="#">Papayaya & Crisps</a></li>
            <li><a href="#">Oatmeal</a></li>
            <li><a href="#">Fresh Bananas</a></li>
        </ul>
    </div>
</div>*@
    @await Component.InvokeAsync("MenuLoaiSPComponent")